# Generated by Django 4.2.1 on 2023-06-30 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
                ('Restaurant_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.restaurantadd')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pizza_name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=500)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(default='abc.jpg', upload_to='Images')),
                ('Restaurant_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.restaurantadd')),
                ('cat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category')),
            ],
            options={
                'db_table': 'Pizza',
            },
        ),
    ]
