# Generated by Django 4.2.1 on 2023-07-04 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_category_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_name', models.CharField(max_length=30)),
                ('Restaurant_city', models.CharField(max_length=30)),
                ('Restaurant_number', models.IntegerField(max_length=12)),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.AlterField(
            model_name='category',
            name='Restaurant_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.restaurant'),
        ),
        migrations.DeleteModel(
            name='Restaurantadd',
        ),
    ]
