# Generated by Django 4.2.1 on 2023-07-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_restaurant_delete_pizza_alter_category_restaurant_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='Images'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
