# Generated by Django 4.2.1 on 2023-07-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_menucategory_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='cat_fk',
        ),
    ]
