# Generated by Django 4.2.1 on 2023-07-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Restaurant_description',
            field=models.CharField(default=1000, max_length=1000),
            preserve_default=False,
        ),
    ]
