# Generated by Django 4.2.3 on 2023-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_deliverydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
